export default {
    ATUALIZAR_PEDIDO: 'atualizarPedido',
    ATUALIZAR_USUARIO: 'atualizarUsuario',
    ATUALIZAR_MESA: 'atualizarMesa',
    ATUALIZAR_PRODUTO: 'atualizarProduto',
    BUSCAR_CATEGORIAS: 'buscarCategorias',
    BUSCAR_PRODUTOS_POR_CATEGORIA: 'buscarProdutosPorCategoria',
    BUSCAR_MESAS: 'buscarMesas',
    BUACAR_USUARIO_LOGADO: 'buscarUsuarioLogado',
    BUSCAR_USUARIOS: 'buscarUsuarios',
    BUSCAR_PEDIDO_POR_MESA: 'buscarPedidoPorMesa',
    BUSCAR_PEDIDOS_FINALIZADOS: 'buscarPedidosFinalizados',
    BUSCAR_PEDIDOS_EMESPERA: 'buscarPedidosEmEspera',
    EFETUAR_LOGIN: 'efetuarLogin',
    EFETUAR_LOGOUT: 'efetuarLogout',
    INSERIR_CATEGORIA: 'inserirCategoria',
    INSERIR_COMANDA: 'inseirComanda',
    INSERIR_PEDIDO: 'inserirPedido',
    INSERIR_PRODUTO: 'inserirNovoProduto',
    INSERIR_USUARIO: 'inserirUsuario',
    INSERIR_MESA: 'inserirMesa',
    REMOVER_PRODUTO: 'removerProduto',
    REMOVER_USUARIO: 'removerUsuario'
}
